# -*- coding: utf-8 -*-
"""sketch

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H5hKIVr4p1o_4aei9GIgL_zKyrWyRijI
"""

pip install opencv-python

import cv2

image=cv2.imread('ironman.jpg.jpeg')

gray_img  = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

invert=cv2.bitwise_not(gray_img)

blur=cv2.GaussianBlur(invert, (21,21),0)

inverted_blur=cv2.bitwise_not(blur)

sketch=cv2.divide(gray_img, inverted_blur, scale=256.0)

cv2.imwrite('sketch.png', sketch)